# Generated by Django 4.2.4 on 2023-09-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingsettings_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('modify_settings_status', 'Изменить статус рассылки')], 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
    ]
