# Generated by Django 4.2.4 on 2023-09-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_mailinglog_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], default='ok', max_length=50, verbose_name='Статус'),
        ),
    ]
